import React from 'react';
import { Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material';

type DemandRow = { role: string; pallets: number; demandPallets: number; kpi: number; trucks: number };
type RoleSummary = { role: string; people: number; hours: number; productiveHours: number };

export default function RoleKpiOverview({ rows, roleSummary, roleMatches }: { rows: DemandRow[]; roleSummary: RoleSummary[]; roleMatches: (left: string, right: string) => boolean }) {
  const visibleRows = rows.filter(row => !['booking', 'banding'].includes(row.role.toLowerCase().replace(/[^a-z]+/g, '')));
  return <Paper className="table-wrap" sx={{ overflowX: 'auto' }}><Typography variant="h6" fontWeight={800} sx={{ mb: 1 }}>Role demand overview</Typography><TableContainer><Table size="small" sx={{ minWidth: 920 }}><TableHead><TableRow>{['Job title', 'Rostered hours', 'Productive hours', 'People', 'Pallets capacity', 'KPI target', 'KPI forecast', 'Capability', 'Trucks'].map(label => <TableCell key={label} sx={{ fontWeight: 800, whiteSpace: 'nowrap' }}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{visibleRows.map(row => { const assigned = roleSummary.find(item => roleMatches(item.role, row.role)); const hours = assigned?.hours ?? 0; const productiveHours = assigned?.productiveHours ?? 0; const people = assigned?.people ?? 0; const forecastKpi = productiveHours > 0 ? row.demandPallets / productiveHours : 0; const capability = row.demandPallets > 0 ? row.pallets / row.demandPallets * 100 : 0; return <TableRow key={row.role}><TableCell sx={{ fontWeight: 700 }}>{row.role}</TableCell><TableCell>{hours.toFixed(1)}</TableCell><TableCell>{productiveHours.toFixed(1)}</TableCell><TableCell>{people}</TableCell><TableCell>{row.pallets.toFixed(1)}</TableCell><TableCell sx={{ fontWeight: 800 }}>{row.kpi.toFixed(1)}</TableCell><TableCell sx={{ color: forecastKpi >= row.kpi ? 'success.main' : 'error.main', fontWeight: 800 }}>{forecastKpi.toFixed(1)}</TableCell><TableCell sx={{ color: capability < 100 ? 'error.main' : 'success.main', fontWeight: 800 }}>{capability.toFixed(1)}%</TableCell><TableCell>{row.trucks.toFixed(1)}</TableCell></TableRow>; })}</TableBody></Table></TableContainer></Paper>;
}
